### ISSUE TITLE
GameTests Article 

### ISSUE THREAD

**Issue by TheOnlyTails** [forgecommunitywiki/wiki-tracker#1]
**Page Topic**
The new GameTest system in 1.17 for unit testing mods. 

**Reason For Request**
It's pretty complex and unintuitive for new users, and it's completely different than anything we've had so far.

**Content**
How to make tests (`@GameTest`,`@GameTestGenerator`), use them in CI (e.g. GH Actions), and how to use the `GameTestHelper`.

**Comment by ChampionAsh5357** [comment]
Added a page on [Game Tests](https://forge.gemwire.uk/wiki/Game_Tests).
