### ISSUE TITLE
A separate `mods.toml` page

### ISSUE THREAD

**Issue by sciwhiz12** [forgecommunitywiki/wiki-tracker#2]
**Page Topic**
Covers the `mods.toml` metadata file, which declares the mods contained within the JAR file. Currently, there is already existing information on this, on the [Proper Mod Structuring]() article.

**Reason For Request**
This was suggested and requested a while ago by @N1K-x in the discord, as they feel it would be better suited as a seperate page on its own rather than being part of the Proper Mod Structuring page.

**Content**
What content should be expanded upon in the page (e.g. method specifications, detailed subtopics, etc.).
The page should detail what the `mods.toml` file is, the properties it may contain for both declaring contained mods and their dependencies, as well as a brief mention of its predecessor, `mcmod.info`.

**Comment by niklaswimmer** [comment]
I have now extracted the information about the `mods.toml` file which was present on the [Proper Mod Structuring](https://forge.gemwire.uk/wiki/Proper_Mod_Structuring#mods.toml_file) article into it's own article: [Mods.toml file](https://forge.gemwire.uk/wiki/Mods.toml_file).
