### ISSUE TITLE
Tag data generation page lacking information on existing provider types.

### ISSUE THREAD

**Issue by AtlaStar** [forgecommunitywiki/wiki-tracker#3]
Currently the wiki page for [tag datagen](https://forge.gemwire.uk/wiki/Datageneration/Tags) only includes information on the existing item and block tag providers, although numerous provider types exist.

It also shows that the page is under construction, and lacks information on custom tag types, or context as to whether a 'custom tag type' is just a direct implementation of `TagsProvider<T>` or something different entirely.

**Comment by ChampionAsh5357** [comment]
[Rewritten](https://forge.gemwire.uk/wiki/Datageneration/Tags) using the [forge docs](https://docs.minecraftforge.net/en/1.19.x/datagen/server/tags/) as a reference/base.
